-- =============================================================================
-- init.sql — 新环境建库入口
-- 完整 DDL 见同目录 schema_full_v1.sql（与 app/models.py 一一对应）
--
-- 执行示例（Windows PowerShell）:
--   Get-Content schema_full_v1.sql | mysql -h127.0.0.1 -P3306 -uroot -p
-- Linux/macOS:
--   mysql -h127.0.0.1 -P3306 -uroot -p < schema_full_v1.sql
-- =============================================================================
